### ISSUE TITLE
What about test framework?

### ISSUE THREAD

**Issue by ddetommaso** [s4hri/pykron#10]
We need a test framework to ensure that new pull requests do not break compatibility and/or cause changes in the current features. Specifically we want:

1. Find a test framework suitable for this project
2. Find a way to automatize the battery test running for each new push on the master branch
3. Define rules and a template for writing tests
4. Write some tests as example

In the following we will discuss possible solutions to address this issue.

**Comment by adamlukomski** [comment]
Proposition 1: pytest
For assertions about the results from each test we either can use the result from futures directly, or StreamIO the PykronLogger and parse it to see if the execution order is correct

EDIT: StringIO from io, stream=StringIO() can be used with logging.StreamHandler(stream) to have access to current log

**Comment by ddetommaso** [comment]
What about migrating our current tests in unittest  (py std library)?

**Comment by ddetommaso** [comment]
Recap

1. Find a test framework suitable for this project  
- unittest (Python std library)

2. Find a way to automatize the battery test running for each new push on the master branch
- travis

3. Define rules and a template for writing tests
- this needs to be moved where the generic workflow is defined

4. Write some tests as example
- done
