### ISSUE TITLE
Licence header

### ISSUE THREAD

**Issue by ddetommaso** [s4hri/pykron#27]
As developers we need the same licence header for each source code file in the repo.

**Comment by ddetommaso** [comment]
I am updating licence header with the following

"""
BSD 2-Clause License

Copyright (c) 2020, Davide De Tommaso (davide.detommaso@iit.it),
                    Adam Lokomski (adam.lukomski@iit.it),
                    Social Cognition in Human-Robot Interaction
                    Istituto Italiano di Tecnologia (IIT)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

**Comment by adamlukomski** [comment]
Lukomski*

~~are we keeping the same in each source code file, or can we make it shorter, like:~~

~~"""~~
~~Pykron: open-source package that let you easily transform any Python function in an asynchronous call~~

~~Copyright (c) 2020 Davide De Tommaso (davide.detommaso@iit.it), Adam Lukomski (adam.lukomski@iit.it),~~
~~Social Cognition in Human-Robot Interaction, IIT~~

~~Distributed under BSD 2-Clause License, please see LICENSE file~~
~~"""~~

Ok, I actually during the writing of that re-read the suggestions for BSD 2-clause, and we are not to modify/shorten the license comment in any file.  But the "All rights reserved" is obsolete and I think can be skipped at this point.
