### ISSUE TITLE
What about identifiers for Task/Request ?

### ISSUE THREAD

**Issue by ddetommaso** [s4hri/pykron#7]
We need to assign an identifier for each task in order to be able to make the debugging easier.

In examples of profiling in Python has been used as identifier

**Function_name (filename:line_nr)**

Floor is open to other proposal.

**Comment by adamlukomski** [comment]
On the topic of identifiers, this is probably not safe because native_id is system-dependant afaik:
(line 152 in face5a1)
```
    def run(self):
        self._thread_id = threading.get_native_id() + 1
```

**Comment by ddetommaso** [comment]
The current proposal is to use as Task/Request identifier the threading.current_thread().ident
